UIText = {
    
    ShopUITitle = "Valhalla Shop",
    TransferUITitle = "Transfer",

    ShopViewOnly = getText("IGUI_Shop_ViewOnly"),
    ShopViewItems = getText("IGUI_Shop_ViewItems"),

    AddShop = getText("IGUI_AddShop"),
    RemoveShop = getText("IGUI_RemoveShop"),

    AddPlayerShop = getText("IGUI_AddPlayerShop"),
    AddPlayerShopFreezer = getText("IGUI_AddPlayerShopFreezer"),
    RemovePlayerShop = getText("IGUI_RemovePlayerShop"),
    RemoveItemsPlayerShop = getText("IGUI_RemoveItemsPlayerShop"),
    RemoveIncomePlayerShop = getText("IGUI_RemoveIncomePlayerShop"),
    ViewIncomePlayerShop = getText("IGUI_ViewIncomePlayerShop"),
    PickupPlayerShop = getText("IGUI_PickupPlayerShop"),
    UnlockContainerPlayerShop = getText("IGUI_UnlockContainerPlayerShop"),
    LockContainerPlayerShop = getText("IGUI_LockContainerPlayerShop"),
    ManagePlayerShop = getText("IGUI_ManagePlayerShop"),
    SetPricePlayerShop = getText("IGUI_SetPricePlayerShop"),
    ChangeSign = getText("IGUI_ChangeSign"),

    Income = getText("IGUI_Income"),
    Get = getText("IGUI_Get"),

    LootAllCoins = getText("IGUI_Loot_All_Coins"),
    CoinsToAccount = getText("IGUI_Coins_To_Account"),
    AccountNeeded = getText("IGUI_Balance_AccountNeeded"),
    Link = getText("IGUI_Balance_Link"),
    Unlink = getText("IGUI_Balance_Unlink"),
    Transfer = getText("IGUI_Balance_Transfer"),
    TransferTo = getText("IGUI_Balance_TransferTo"),
    Send = getText("IGUI_Balance_Send"),
    Shop = getText("IGUI_Shop"),
    Search = getText("IGUI_Shop_Search"),
    ClearCart = getText("IGUI_Shop_ClearCart"),
    BuyCart = getText("IGUI_Shop_BuyCart"),
    Sell = getText("IGUI_Shop_Sell"),
    Balance = getText("IGUI_Shop_Balance"),
    Total = getText("IGUI_Shop_Total"),
    Cancel = getText("UI_Cancel"),
    Contains = getText("IGUI_Contains"),
    DropOnFloor = getText("IGUI_Shop_DropOnFloor"),
}